/* SimpleCalculator.java */
/* Simple Swing Calculator
 *
 * Copyright 2016 Ankit Pati <ankitpati@gmail.com>
 *
 * This  software is  free software;  you can redistribute it and/or  modify  it
 * under the terms of the  GNU Lesser General Public License as published by the
 * Free Software Foundation;  either  version 3  of the  License,  or  (at  your
 * option) any later version.
 *
 * This software is distributed in the hope that it will be useful, but  WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You  should  have received a copy of the GNU Lesser  General  Public  License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

package jcalc;

import java.awt.event.*;
import javax.swing.*;

public class SimpleCalculator extends JFrame {
    final static long serialVersionUID = 0l;

    public SimpleCalculator() {
        initComponents();
        getRootPane().setDefaultButton(calculate);
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) plaf.addItem(info.getName());
        plaf.setSelectedItem("Nimbus");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eraseToLeft = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        decimalPoint = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        value = new javax.swing.JTextField();
        num9 = new javax.swing.JButton();
        power = new javax.swing.JButton();
        exponentConstant = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        root = new javax.swing.JButton();
        storedValue = new javax.swing.JLabel();
        mul = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        div = new javax.swing.JButton();
        add = new javax.swing.JButton();
        operation = new javax.swing.JLabel();
        plaf = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setAlwaysOnTop(true);
        setResizable(false);

        eraseToLeft.setText("⌫");
        eraseToLeft.setFocusable(false);
        eraseToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseToLeftActionPerformed(evt);
            }
        });

        num5.setText("5");
        num5.setFocusable(false);
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        clear.setText("c");
        clear.setFocusable(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        num4.setText("4");
        num4.setFocusable(false);
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        sub.setText("-");
        sub.setFocusable(false);
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        decimalPoint.setText(".");
        decimalPoint.setFocusable(false);
        decimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPointActionPerformed(evt);
            }
        });

        num0.setText("0");
        num0.setFocusable(false);
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        calculate.setText("=");
        calculate.setFocusable(false);
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        num3.setText("3");
        num3.setFocusable(false);
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        num8.setText("8");
        num8.setFocusable(false);
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        num1.setText("1");
        num1.setFocusable(false);
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        value.setEditable(false);
        value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valueKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valueKeyPressed(evt);
            }
        });

        num9.setText("9");
        num9.setFocusable(false);
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        power.setText("^");
        power.setFocusable(false);
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        exponentConstant.setText("E");
        exponentConstant.setFocusable(false);
        exponentConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentConstantActionPerformed(evt);
            }
        });

        num6.setText("6");
        num6.setFocusable(false);
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        num2.setText("2");
        num2.setFocusable(false);
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        root.setText("√");
        root.setFocusable(false);
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        storedValue.setText("0.0");

        mul.setText("✕");
        mul.setFocusable(false);
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        num7.setText("7");
        num7.setFocusable(false);
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformedHandler(evt);
            }
        });

        div.setText("/");
        div.setFocusable(false);
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        add.setText("+");
        add.setFocusable(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformedHandler(evt);
            }
        });

        operation.setText("=");

        plaf.setToolTipText("Look and Feel");
        plaf.setFocusable(false);
        plaf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plafItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(plaf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(calculate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(power)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(root))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eraseToLeft))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(num4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(num7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(num1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(exponentConstant)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num0)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(decimalPoint)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add)
                                .addComponent(sub)
                                .addComponent(mul)
                                .addComponent(div)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add, calculate, clear, decimalPoint, div, exponentConstant, mul, num0, num1, num2, num3, num4, num5, num6, num7, num8, num9, power, root, sub});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operation)
                    .addComponent(storedValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eraseToLeft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(power)
                    .addComponent(root)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4)
                    .addComponent(num5)
                    .addComponent(num6)
                    .addComponent(sub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7)
                    .addComponent(num8)
                    .addComponent(num9)
                    .addComponent(mul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num0)
                    .addComponent(div)
                    .addComponent(decimalPoint)
                    .addComponent(exponentConstant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add, calculate, clear, decimalPoint, div, exponentConstant, mul, num0, num1, num2, num3, num4, num5, num6, num7, num8, num9, power, root, sub, value});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        value.setText("");
        storedValue.setText("0.0");
        operation.setText("=");
    }//GEN-LAST:event_clearActionPerformed

    private void decimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPointActionPerformed
        int i;
        String orig;

        orig = value.getText();

        if(orig.contains(".") || orig.contains("E")) return;
        if(orig.contains("I") || orig.contains("N")) value.setText(orig = "");
        /* Checking for these letters because
            E = Exponent
            I = Infinity
            N = NaN
        */

        value.setText(orig + '.');
    }//GEN-LAST:event_decimalPointActionPerformed

    private void eraseToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseToLeftActionPerformed
        String orig;
        orig = value.getText();
        if(orig.length() == 0) return;
        value.setText(orig.substring(0, orig.length() - 1));
    }//GEN-LAST:event_eraseToLeftActionPerformed

    private void exponentConstantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentConstantActionPerformed
        int i;
        String orig;
        orig = value.getText();
        if("".equals(orig) || "-".equals(orig) || orig.contains("I") || orig.contains("N")) return;
        if(!orig.contains("E")) value.setText(orig + 'E');
    }//GEN-LAST:event_exponentConstantActionPerformed

    private void numActionPerformedHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformedHandler
        if(value.getText().contains("I") || value.getText().contains("N")) value.setText("");
        value.setText(value.getText() + evt.getActionCommand());
    }//GEN-LAST:event_numActionPerformedHandler

    private void calculationActionPerformedHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformedHandler
        double previousValue, currentValue;
        String orig, command, previousCommand;

        orig = value.getText();
        command = evt.getActionCommand();
        previousCommand = operation.getText();

        if("".equals(orig) || orig.charAt(orig.length() - 1) == 'E'){
            if("-".equals(command)) value.setText(orig + '-');
            else if(!"=".equals(command)) operation.setText(command);
            return;
        }

        if(orig.charAt(orig.length() - 1) == '-'){
            if(!"=".equals(command)) operation.setText(command);
            return;
        }

        try{
            previousValue = Double.parseDouble(storedValue.getText());
            currentValue = Double.parseDouble(orig);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Invalid Number!\nPress C to clear the input.");
            return;
        }

        value.setText("");

        switch(previousCommand){
        case "+":
            previousValue += currentValue;
            break;
        case "-":
            previousValue -= currentValue;
            break;
        case "✕":
            previousValue *= currentValue;
            break;
        case "/":
            previousValue /= currentValue;
            break;
        case "^":
            previousValue = Math.pow(previousValue, currentValue);
            break;
        case "√":
            previousValue = Math.pow(currentValue, 1.0 / previousValue);
            break;
        case "=":
            previousValue = currentValue;
            break;
        }

        operation.setText(command);
        storedValue.setText(String.valueOf(previousValue));

        if("=".equals(command)) value.setText(String.valueOf(previousValue));
    }//GEN-LAST:event_calculationActionPerformedHandler

    private void plafItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plafItemStateChanged
        SwingUtilities.invokeLater(() -> {
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                    if (plaf.getSelectedItem().equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                SwingUtilities.updateComponentTreeUI(this);
                pack();
            }
            catch (Exception ex) {
                System.err.println("Cannot set "+plaf.getSelectedItem()+" theme.");
            }
        });
    }//GEN-LAST:event_plafItemStateChanged

    private void valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueKeyTyped
        switch (evt.getKeyChar()) {
        case '1':
            num1.doClick();
            break;
        case '2':
            num2.doClick();
            break;
        case '3':
            num3.doClick();
            break;
        case '4':
            num4.doClick();
            break;
        case '5':
            num5.doClick();
            break;
        case '6':
            num6.doClick();
            break;
        case '7':
            num8.doClick();
            break;
        case '8':
            num8.doClick();
            break;
        case '9':
            num9.doClick();
            break;
        case '0':
            num0.doClick();
            break;
        case '.':
            decimalPoint.doClick();
            break;
        case 'e':   /* intended fall-through */
        case 'E':
            exponentConstant.doClick();
            break;
        case '=':
            calculate.doClick();
            break;
        case '\b':
            eraseToLeft.doClick();
            break;
        case 'c':   /* intended fall-through */
        case 'C':
            clear.doClick();
            break;
        case '+':
            add.doClick();
            break;
        case '-':
            sub.doClick();
            break;
        case '*':   /* intended fall-through */
        case 'x':
        case 'X':
            mul.doClick();
            break;
        case '/':
            div.doClick();
            break;
        case '^':
            power.doClick();
            break;
        case 'r':
            root.doClick();
            break;
        default:
            break;
        }
    }//GEN-LAST:event_valueKeyTyped

    private void valueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueKeyPressed
        switch (evt.getKeyCode()) {
        case KeyEvent.VK_UP:
            plaf.setSelectedIndex((plaf.getSelectedIndex() == 0 ? plaf.getItemCount() : plaf.getSelectedIndex()) - 1);
            break;
        case KeyEvent.VK_DOWN:
            plaf.setSelectedIndex(plaf.getSelectedIndex() == plaf.getItemCount() - 1 ? 0 : plaf.getSelectedIndex() + 1);
            break;
        default:
            break;
        }
    }//GEN-LAST:event_valueKeyPressed

    public static void main(String args[]) {
        SimpleCalculator sc = new SimpleCalculator();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JButton decimalPoint;
    private javax.swing.JButton div;
    private javax.swing.JButton eraseToLeft;
    private javax.swing.JButton exponentConstant;
    private javax.swing.JButton mul;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JLabel operation;
    private javax.swing.JComboBox plaf;
    private javax.swing.JButton power;
    private javax.swing.JButton root;
    private javax.swing.JLabel storedValue;
    private javax.swing.JButton sub;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
/* end of SimpleCalculator.java */
